# Generated by Django 3.1.2 on 2020-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201103_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('points', models.IntegerField()),
                ('win', models.IntegerField()),
                ('loose', models.IntegerField()),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
    ]
