# Generated by Django 3.1.2 on 2020-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_lost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_shot',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='loose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.IntegerField(null=True),
        ),
    ]
