# Generated by Django 3.1.2 on 2020-11-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201106_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_shot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
