# Generated by Django 3.1.2 on 2020-11-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Matchday',
            new_name='Match',
        ),
    ]
