# Generated by Django 3.1.2 on 2020-11-11 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201111_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchweek',
            options={'verbose_name_plural': 'Match Weeks'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_weeks', to='core.matchweek'),
        ),
        migrations.AddField(
            model_name='matchweek',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
