# Generated by Django 3.1.2 on 2020-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201111_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_goals',
            field=models.IntegerField(null=True),
        ),
    ]
