# Generated by Django 3.1.2 on 2020-12-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201126_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchweek',
            name='week',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
