# Generated by Django 3.1.2 on 2020-12-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201202_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchweek',
            options={'ordering': ['-week'], 'verbose_name_plural': 'Match Weeks'},
        ),
    ]
