# Generated by Django 3.1.2 on 2020-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201208_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('Goalkeeper', 'Bramkarz'), ('Defender', 'Obronca'), ('Midfielder', 'Pomocnik'), ('Forward', 'Napastnik')], max_length=20)),
            ],
            options={
                'ordering': ['position', 'last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
