# Generated by Django 3.1.2 on 2020-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Bramkarz', 'Bramkarz'), ('Obrońca', 'Obrońca'), ('Pomocnik', 'Pomocnik'), ('Napastnik', 'Napastnik')], max_length=20),
        ),
    ]
