# Generated by Django 3.1.2 on 2020-12-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_team_matches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-points', '-goals_shot', '-goals_lost', 'name']},
        ),
    ]
