# Generated by Django 3.1.2 on 2020-12-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201218_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_week', 'date'], 'verbose_name_plural': 'Matches'},
        ),
    ]
