# Generated by Django 3.1.2 on 2021-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_nextmatchweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_week', models.IntegerField()),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
                ('home_team_goals', models.IntegerField(blank=True, null=True)),
                ('away_team_goals', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nextmatchweek',
            options={'verbose_name_plural': 'Next matchweek'},
        ),
    ]
