# Generated by Django 3.1.2 on 2021-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210303_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtest',
            name='away_team_goals',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchtest',
            name='home_team_goals',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
