# Generated by Django 3.1.2 on 2021-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210303_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchtest',
            name='days',
        ),
        migrations.AddField(
            model_name='matchtest',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
