# Generated by Django 3.1.2 on 2021-03-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210305_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtest',
            options={'ordering': ['-date']},
        ),
    ]
