# Generated by Django 3.1.2 on 2021-03-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210305_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtest',
            options={'ordering': ['match_week', 'date']},
        ),
    ]
