# Generated by Django 3.1.2 on 2021-03-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210305_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchtest',
            options={'ordering': ['-match_week', 'date']},
        ),
    ]
