# Generated by Django 3.1.2 on 2021-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210310_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
